// Mock City Hall Profile
export const mockCityHall = {
  id: "ch-001",
  user_id: "user-001",
  name: "Primăria Municipiului București",
  tax_id: "RO12345678",
  contact_person_name: "Ion Popescu",
  contact_person_email: "ion.popescu@pmb.ro",
  contact_person_phone: "0721123456",
  locality: "București",
  address: "Bulevardul Regina Elisabeta 47",
  created_at: new Date().toISOString(),
};

// Mock User
export const mockUser = {
  id: "user-001",
  email: "primarie@bucuresti.ro",
  created_at: new Date().toISOString(),
};

// Mock Services
export const mockServices = [
  { id: "srv-001", name: "Alimentare cu apă potabilă", is_active: true },
  { id: "srv-002", name: "Canalizare și epurare", is_active: true },
  { id: "srv-003", name: "Distribuție energie electrică", is_active: true },
  { id: "srv-004", name: "Distribuție gaze naturale", is_active: true },
  { id: "srv-005", name: "Salubrizare și gestiunea deșeurilor", is_active: true },
  { id: "srv-006", name: "Transport public local", is_active: true },
  { id: "srv-007", name: "Iluminat public", is_active: true },
  { id: "srv-008", name: "Întreținere spații verzi", is_active: true },
  { id: "srv-009", name: "Administrare drumuri locale", is_active: true },
  { id: "srv-010", name: "Servicii de termoficare", is_active: true },
];

// Mock Providers
export const mockProviders = [
  { id: "prv-001", name: "Apa Nova București", tax_id: "RO14787830", is_active: true },
  { id: "prv-002", name: "E-Distribuție Muntenia", tax_id: "RO14507322", is_active: true },
  { id: "prv-003", name: "ENGIE România", tax_id: "RO13093222", is_active: true },
  { id: "prv-004", name: "Supercom S.A.", tax_id: "RO16387080", is_active: true },
  { id: "prv-005", name: "STB S.A.", tax_id: "RO15283020", is_active: true },
  { id: "prv-006", name: "Luxten Lighting Company", tax_id: "RO1568905", is_active: true },
  { id: "prv-007", name: "Alpab S.A.", tax_id: "RO361970", is_active: true },
  { id: "prv-008", name: "Compania de Drumuri București", tax_id: "RO41245678", is_active: true },
  { id: "prv-009", name: "ELCEN București", tax_id: "RO14282455", is_active: true },
  { id: "prv-010", name: "Veolia Energie București", tax_id: "RO37860108", is_active: true },
];

// Mock Initial Requests
export const mockInitialRequests = [
  {
    id: "req-001",
    city_hall_id: "ch-001",
    city_hall_name: "Primăria Municipiului București",
    city_hall_tax_id: "RO12345678",
    contact_person_name: "Ion Popescu",
    contact_person_email: "ion.popescu@pmb.ro",
    contact_person_phone: "0721123456",
    locality: "București",
    title: "Extindere rețea apă potabilă - Sector 3",
    description: "Solicitare pentru extinderea rețelei de alimentare cu apă potabilă în zona Titan, pentru a deservi noile blocuri construite.",
    service_id: "srv-001",
    service_name: "Alimentare cu apă potabilă",
    provider_id: "prv-001",
    provider_name: "Apa Nova București",
    provider_tax_id: "RO14787830",
    status: "accepted",
    status_notes: "Lucrările vor începe în luna următoare conform planificării.",
    has_estimated_start_date: true,
    estimated_start_date: "2025-02-15",
    request_date: "2025-01-10",
    created_at: "2025-01-10T09:30:00Z",
  },
  {
    id: "req-002",
    city_hall_id: "ch-001",
    city_hall_name: "Primăria Municipiului București",
    city_hall_tax_id: "RO12345678",
    contact_person_name: "Ion Popescu",
    contact_person_email: "ion.popescu@pmb.ro",
    contact_person_phone: "0721123456",
    locality: "București",
    title: "Modernizare iluminat public - Bulevardul Unirii",
    description: "Înlocuirea corpurilor de iluminat existente cu LED-uri de ultimă generație pentru eficiență energetică.",
    service_id: "srv-007",
    service_name: "Iluminat public",
    provider_id: "prv-006",
    provider_name: "Luxten Lighting Company",
    provider_tax_id: "RO1568905",
    status: "pending",
    status_notes: null,
    has_estimated_start_date: false,
    estimated_start_date: null,
    request_date: "2025-01-18",
    created_at: "2025-01-18T14:15:00Z",
  },
  {
    id: "req-003",
    city_hall_id: "ch-001",
    city_hall_name: "Primăria Municipiului București",
    city_hall_tax_id: "RO12345678",
    contact_person_name: "Ion Popescu",
    contact_person_email: "ion.popescu@pmb.ro",
    contact_person_phone: "0721123456",
    locality: "București",
    title: "Amenajare spații verzi - Parcul IOR",
    description: "Plantare arbori și arbuști decorativi, amenajare alei pietonale și zone de recreere.",
    service_id: "srv-008",
    service_name: "Întreținere spații verzi",
    provider_id: "prv-007",
    provider_name: "Alpab S.A.",
    provider_tax_id: "RO361970",
    status: "rejected",
    status_notes: "Buget insuficient pentru anul curent. Vă rugăm să retransmiteți cererea în trimestrul I 2026.",
    has_estimated_start_date: true,
    estimated_start_date: "2025-03-01",
    request_date: "2025-01-05",
    created_at: "2025-01-05T11:00:00Z",
  },
  {
    id: "req-004",
    city_hall_id: "ch-001",
    city_hall_name: "Primăria Municipiului București",
    city_hall_tax_id: "RO12345678",
    contact_person_name: "Ion Popescu",
    contact_person_email: "ion.popescu@pmb.ro",
    contact_person_phone: "0721123456",
    locality: "București",
    title: "Reabilitare conductă gaze - Strada Victoriei",
    description: "Înlocuirea conductei de gaze naturale pe o lungime de 500m datorită uzurii avansate.",
    service_id: "srv-004",
    service_name: "Distribuție gaze naturale",
    provider_id: "prv-003",
    provider_name: "ENGIE România",
    provider_tax_id: "RO13093222",
    status: "accepted",
    status_notes: "Aprobat. Coordonare cu alte lucrări în zonă.",
    has_estimated_start_date: true,
    estimated_start_date: "2025-02-20",
    request_date: "2025-01-12",
    created_at: "2025-01-12T08:45:00Z",
  },
  {
    id: "req-005",
    city_hall_id: "ch-001",
    city_hall_name: "Primăria Municipiului București",
    city_hall_tax_id: "RO12345678",
    contact_person_name: "Ion Popescu",
    contact_person_email: "ion.popescu@pmb.ro",
    contact_person_phone: "0721123456",
    locality: "București",
    title: "Colectare selectivă deșeuri - Zona Pipera",
    description: "Implementare sistem de colectare selectivă în zona rezidențială Pipera, cu pubele diferențiate.",
    service_id: "srv-005",
    service_name: "Salubrizare și gestiunea deșeurilor",
    provider_id: "prv-004",
    provider_name: "Supercom S.A.",
    provider_tax_id: "RO16387080",
    status: "pending",
    status_notes: null,
    has_estimated_start_date: false,
    estimated_start_date: null,
    request_date: "2025-01-20",
    created_at: "2025-01-20T16:30:00Z",
  },
];

// Mock Initial Notifications
export const mockInitialNotifications = [
  {
    id: "notif-001",
    user_id: "user-001",
    title: "Cerere acceptată",
    message: "Cererea \"Extindere rețea apă potabilă - Sector 3\" a fost acceptată de Apa Nova București.",
    type: "success",
    is_read: false,
    created_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "notif-002",
    user_id: "user-001",
    title: "Cerere respinsă",
    message: "Cererea \"Amenajare spații verzi - Parcul IOR\" a fost respinsă. Verificați motivul în detalii.",
    type: "error",
    is_read: false,
    created_at: "2025-01-08T14:30:00Z",
  },
  {
    id: "notif-003",
    user_id: "user-001",
    title: "Cerere în procesare",
    message: "Cererea \"Reabilitare conductă gaze\" este în curs de analiză de către ENGIE România.",
    type: "info",
    is_read: true,
    created_at: "2025-01-13T09:15:00Z",
  },
  {
    id: "notif-004",
    user_id: "user-001",
    title: "Actualizare status",
    message: "Cererea \"Reabilitare conductă gaze - Strada Victoriei\" a fost acceptată.",
    type: "success",
    is_read: true,
    created_at: "2025-01-14T11:45:00Z",
  },
];

// Helper function to generate unique IDs
export const generateId = () => {
  return "id-" + Math.random().toString(36).substr(2, 9) + "-" + Date.now();
};
